export const ActionTypes ={
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_CARTS: 'SET_CARTS',
    ADD_ITEM_INTO_CART : 'ADD_ITEM_INTO_CART',
    EDIT_QUANTITY_CART_DUPLICATE_ID: 'EDIT_QUANTITY_CART_DUPLICATE_',
    DELETE_ITEM_INTO_CART:'DELETE_ITEM_INTO_CART',
    INCREMENT_NUMBER_ITEM_IN_SHOPPING_CART:'INCREMENT_NUMBER_ITEM_IN_SHOPPING_CART',
    DECREMENT_NUMBER_ITEM_IN_SHOPPING_CART:'DECREMENT_NUMBER_ITEM_IN_SHOPPING_CART',
    CHECKED_CHECKBOX_PRODUCT_IN_SHOPPINGCART:'CHECKED_CHECKBOX_PRODUCT_IN_SHOPPINGCART',
    CHECKED_ITEM_SHOPPINGCART:'CHECKED_ITEM_SHOPPINGCART'
}